content/sitepages/fishing-license-requirements.md
This page was missing from new site. I was able to copy old content to this new page.
=> Adding this page - was missing from new site.

layouts/sitepages/meeting-planners-sub.html, layouts/sitepages/meeting-planners.html
Moved gallery asset link to bottom of Meeting Planners sidebar and added gallery asset link to the meeting planners sub page sidebar
=> Fix sidebar menu

content/lodgingitems/itty-bitty-inn.md
Forestry is creating incorrect data formatting. Had to fix it here so the property showed up
=> Fixed cost data and amenities data

content/lodgingitems/itty-bitty-inn.md
Had to fix property category and cost fields after Forestry commit.
=> Fixed property category and cost fields

data/env.yaml, layouts/partials/lodging/cost.html, layouts/partials/lodging/lodgingAmenities.html, layouts/partials/lodging/propertyCategory.html
=> Fix lodging templates to work with content schema

.forestry/front_matter/templates/home.yml, content/_index.md
=> Reset the homepage slider to default behaviour and add URL to CMS

content/blog/2015-08-31-local-hero-running-legend-steve-prefontaine-honored-this-month.md
=> Content wider than screen

layouts/partials/hd.html
Adding link to Coronavirus page.
=> Coronavirus navigation change

.forestry/front_matter/templates/store.yml, .forestry/settings.yml, content/store/_index.md
Pending categories confirm.
Fixes #114
=> Edit Forestry files.

layouts/index.html
=> Supports slide link in mobile carousel

layouts/partials/tnd-snipcart/AddProductData.html
=> Add absURL to product button image

content/adventure/clamming.md, content/adventure/crabbing-clamming.md, content/adventure/entertainment-and-nightlife.md, content/adventure/gaming.md, content/event/33rd-annual-holiday-lights-at-shore-acres.md, content/event/4th-annual-oregons-adventure-coast-charleston-salmon-run.md, content/event/annual-bay-area-fun-festival-2019.md, content/event/annual-cruz-the-coos.md, content/event/annual-prefontaine-memorial-run.md, content/sitepages/15-off-storm-watching-lodging-special.md, content/sitepages/_index.md, content/sitepages/charleston.md, content/sitepages/contact-us.md, content/sitepages/coos-bay.md, content/sitepages/fall15.md, content/sitepages/fishing-license-requirements.md, content/sitepages/medical-urgent-dental-services.md, content/sitepages/north-bend.md, content/sitepages/regis-page.md, content/sitepages/relocation-info-request.md, content/sitepages/short-codes-page.md, content/sitepages/traveler-s-information.md, layouts/shortcodes/columns.html
=> Update columns divider

layouts/partials/footer.html
=> Add privacy link to footer

config/_default/params.yaml, package-lock.json, package.json
=> Use selfhost meili 0.28.0

assets/js/main.js, assets/sass/modules/_standard-nav.scss, layouts/_default/list.html, layouts/archives/list.html, layouts/blog/list.html, layouts/blog/single.html, layouts/unpublishedblogs/list.html, layouts/unpublishedblogs/single.html, resources/_gen/assets/scss/sass/main.scss_f300667da4f5b5f84e1a9e0702b2fdde.content
=> Add temporary fix to mobile sidebar

layouts/shortcodes/ctas.html
Fixes Make CTA links open in new window #260
=> Add target _blank to CTA links

.cloudcannon/config/_index.js, .cloudcannon/config/collections/posts.js, .cloudcannon/config/collections/trip_ideas.js, .cloudcannon/config/commons.js, .cloudcannon/config/inputs.js
Latest client feedbacks
Fixes #264
=> Improve CMS

layouts/partials/head.html
=> Fix Google Map search

assets/tnd-search/instantsearch/widgets.js, layouts/partials/func/GetOTIS.html, layouts/partials/transformers/dining.html
=> Add new Dining category

config/_default/params.yaml, layouts/partials/transformers/dining.html
=> Otis API / Filter page: cater for `address2`

content/index-es.md, content/products/_index.md, data/redirects.yaml, layouts/partials/hd.html
=> Remove the Store
